"""Initial migration

Revision ID: 3a04e122fab7
Revises: 94e84f5a6d6b
Create Date: 2025-03-03 14:21:05.650609

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a04e122fab7'
down_revision: Union[str, None] = '94e84f5a6d6b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('multiplayer', 'max_players',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('multiplayer', 'current_players',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('multiplayer', 'status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               nullable=True)
    op.create_foreign_key(None, 'multiplayer', 'game_sessions', ['session_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'multiplayer', type_='foreignkey')
    op.alter_column('multiplayer', 'status',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('multiplayer', 'current_players',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('multiplayer', 'max_players',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
