"""Initial migration

Revision ID: 51f79acc3dcd
Revises: 52ad865f851b
Create Date: 2025-03-03 15:18:34.060511

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51f79acc3dcd'
down_revision: Union[str, None] = '52ad865f851b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game_sessions', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('game_sessions', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.alter_column('game_sessions', 'status',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=20),
               nullable=False)
    op.alter_column('multiplayer', 'max_players',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('multiplayer', 'current_players',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('multiplayer', 'status',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=20),
               nullable=False)
    op.drop_constraint('multiplayer_session_id_fkey', 'multiplayer', type_='foreignkey')
    op.drop_constraint('multiplayer_game_id_fkey', 'multiplayer', type_='foreignkey')
    op.drop_column('multiplayer', 'game_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('multiplayer', sa.Column('game_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('multiplayer_game_id_fkey', 'multiplayer', 'games', ['game_id'], ['id'])
    op.create_foreign_key('multiplayer_session_id_fkey', 'multiplayer', 'game_sessions', ['session_id'], ['id'])
    op.alter_column('multiplayer', 'status',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('multiplayer', 'current_players',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('multiplayer', 'max_players',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('game_sessions', 'status',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=50),
               nullable=True)
    op.drop_column('game_sessions', 'updated_at')
    op.drop_column('game_sessions', 'created_at')
    # ### end Alembic commands ###
