"""Initial migration

Revision ID: 80a05e8490d8
Revises: 73fcc662477a
Create Date: 2025-03-03 13:54:37.131678

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80a05e8490d8'
down_revision: Union[str, None] = '73fcc662477a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('game_sessions', 'session_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game_sessions', sa.Column('session_id', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
