"""Initial migration

Revision ID: 94e84f5a6d6b
Revises: 80a05e8490d8
Create Date: 2025-03-03 14:01:40.032407

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94e84f5a6d6b'
down_revision: Union[str, None] = '80a05e8490d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('multiplayer', sa.Column('game_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'multiplayer', 'games', ['game_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'multiplayer', type_='foreignkey')
    op.drop_column('multiplayer', 'game_id')
    # ### end Alembic commands ###
