"""Initial migration

Revision ID: a346e319da95
Revises: b7964ac258e4
Create Date: 2025-03-03 13:29:09.433434

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a346e319da95'
down_revision: Union[str, None] = 'b7964ac258e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('multiplayer', 'game_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('multiplayer', sa.Column('game_id', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
