"""Initial migration

Revision ID: b6d1b5942c33
Revises: 51f79acc3dcd
Create Date: 2025-03-03 15:31:08.906798

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6d1b5942c33'
down_revision: Union[str, None] = '51f79acc3dcd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('multiplayer', sa.Column('game_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'multiplayer', 'games', ['game_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'multiplayer', type_='foreignkey')
    op.drop_column('multiplayer', 'game_id')
    # ### end Alembic commands ###
