"""initial migration

Revision ID: e23f69c91468
Revises: 2371418a7b46
Create Date: 2025-03-06 23:07:48.870930

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e23f69c91468'
down_revision: Union[str, None] = '2371418a7b46'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('russian_roulette', sa.Column('game_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'russian_roulette', 'games', ['game_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'russian_roulette', type_='foreignkey')
    op.drop_column('russian_roulette', 'game_id')
    # ### end Alembic commands ###
